import { ProductItem } from "../models/product-item.model";
export const productData: ProductItem[] = [
    { name: "Love Potion Latte", image: "assets/images/love-potion.jpg", price: 4.50, quantity: 1},
    { name: "Dark Cherry Mocha", image: "assets/images/cherry-cold-brew.jpg", price: 5.00, quantity: 1 },
    { name: "Cookie Butter Latte", image: "assets/images/cookie-butter-latte.jpg", price: 4.20, quantity: 1 },
    { name: "Horchata Cold Brew", image: "assets/images/horchata-cold-brew.jpg", price: 5.10, quantity: 1 },
    { name: "Iced Biscoff Latte", image: "assets/images/iced-biscof.jpg", price: 4.80, quantity: 1 },
    { name: "Vanilla Sweet Cream", image: "assets/images/vanilla-sweet-cream.jpg", price: 4.70 , quantity: 1},
    { name: "Citrus Cardamomo Coffee", image: "assets/images/citrus-coffee.jpg", price: 5.20 , quantity: 1},
    { name: "Hot Mocha Latte", image: "assets/images/hot-mocha.jpg", price: 4.90, quantity: 1 },
    { name: "Iced Cherry Chai", image: "assets/images/iced-cherry-chai.jpg", price: 5.00, quantity: 1 },
    { name: "Apple Crisp Latte", image: "assets/images/apple-crisp.jpg", price: 5.30, quantity: 1 },
    { name: "Mushroom Coffee Iced Latte", image: "assets/images/mushroom-coffee.jpg", price: 5.30, quantity: 1 },
    { name: "Bluebrry Iced Latte", image: "assets/images/blueberry-iced.jpg", price: 5.30, quantity: 1 },
    { name: "Latte", image: "assets/images/latte.jpg", price: 5.30, quantity: 1 },
    { name: "Iced Vanilla Almond Milk Latte", image: "assets/images/iced-vanilla.jpg", price: 5.30, quantity: 1 },
    { name: "Banana Cream Iced Latte", image: "assets/images/banana-cream.jpg", price: 5.30, quantity: 1 },
    { name: "ButtermilkRaspberry Muffin", image: "assets/images/raspberry-muffin.jpg", price: 4.50, quantity: 1 },
    { name: "Apple Cinnamon Crumb Muffin", image: "assets/images/apple-muffin.jpg", price: 5.00, quantity: 1 },
    { name: "Cinnamon Roll Muffin", image: "assets/images/cinnamon-muffin.jpg", price: 4.20, quantity: 1 },
    { name: "Coffee Muffin", image: "assets/images/coffee-muffin.jpg", price: 5.10, quantity: 1 },
    { name: "Triple Chocolate Muffin", image: "assets/images/chocolate-muffin.jpg", price: 4.80, quantity: 1 },
    { name: "Vanilla Muffin", image: "assets/images/vanilla-muffin.jpg", price: 4.70, quantity: 1 },
    { name: "Banana Bread", image: "assets/images/banana-bread.jpg", price: 5.20, quantity: 1 },
    { name: "Carrot Cake", image: "assets/images/carrot-cake.jpg", price: 4.90, quantity: 1 },
    { name: "French Croissant", image: "assets/images/croissant.jpg", price: 5.00, quantity: 1 },
    { name: "Chocolate Cookie", image: "assets/images/chocolate-cookie.jpg", price: 5.30, quantity: 1 },
    { name: "Casa Coffee", image: "assets/images/casa-coffee.jpg", price: 40.50, quantity: 1 },
    { name: "Flor del Sol", image: "assets/images/flor-coffee.jpg", price: 55.00, quantity: 1 },
    { name: "Willie's Remedy", image: "assets/images/willie.jpg", price: 48.20, quantity: 1 },
    { name: "Coffee Bros", image: "assets/images/coffee-bros.jpg", price: 53.10, quantity: 1 },
    { name: "Big Bear", image: "assets/images/big-bear.jpg", price: 49.70, quantity: 1 },

  ];